### ISSUE TITLE
Move left panel to menus at top

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-snodas-ng#1]
The legacy application had a panel on the left with documentation and other tabs.  This area does not get used very often and takes up map space that could be otherwise useful.  I suggest moving the tabs to menus at the top, similar to InfoMapper, convert the HTML to markdown that is more easily edited, and use showdown popup dialogs to show the content.  This will also demonstrate a use of the OpenWaterFoundation/showdown library.

**Comment by smalers** [comment]
Actually, it looks like the work from Jessica already moved those to menus so that is OK.  Technical considerations are:

1. It is desirable to move to Markdown so the content can be more easily edited.
2. Viewing across the whole area is OK for now but might implement popup documentation later.
3. Links opening in new tabs, such as for user and developer documentation is OK.

**Comment by Nightsphere** [comment]
The menus have been moved, and markdown is currently being used to display the content pages. Data, Docs, About. Closing this issue.
