### ISSUE TITLE
Select Date and Select Basin appear different

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-snodas-ng#15]
The ***Select Data*** and ***Select Basin*** controls have different style.  Make consistent to look like ***Select Basin***.  Also, the cursor 

Also, change the label from ***Current SNODAS Date*** to ***Selected SNODAS Date*** to match basin language.

**Comment by Nightsphere** [comment]
The label and control style have been changed. Before I close the issue, it seemed you had a thought about the cursor, but never finished writing the sentence. Was there something else that needed to be done there?
