### ISSUE TITLE
Animation feedback

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-snodas-ng#17]
The animation date selector needs to be fixed:

1. The animation will most often be a portion of the recent year, for example current water year October to current date or maybe January 1 to current date.  The current default shows the first historical date. It will be a pain for users to get to the current year.
2. Can tooltip be shown to show format.
3. Use ISO 8601 format if possible.  It shows MM/DD/YYYY format in some cases?  It does show ISO in some cases.
4. Using the date selector is confusing to me.  Do you pick two dates in any months and the tool figures out the spanning period from that?
5. I typed `2021-01-01` and tried to use the arrow to move past `to` and it would not let me.  When I clicked the mouse after `to` it changed the date to `2020-12-31`.  The behavior is confusing.
6. Similarly, I entered `2021-04-17` after the `to` and when clicking somewhere else it changed to `2021-04-16`.  The behavior is inconsistent.
7. Pressing the pause button should enable the start and restart buttons and disable the pause button.
8. I recommend that if restart is pressed that it does not automatically start playing.  For example, I may want to change the increment before pressing play.

**Comment by smalers** [comment]
The Material date selector seems to be misbehaving.  Rather than continue to fight that, with negative impacts on users, it may be helpful to provide some quick picks to facilitate picking a date range.  For example have a choice or radio box that fits into the layout with the following choices.  We definitely don't want to waste a lot of time on this.

* Current calendar year (2020-01-01 to current day)
* Current water year (2020-10-01 to current day)

I am being verbose for illustration but may not need that.

**Comment by Nightsphere** [comment]
The new method has been implemented and used for a few months now. Start and end dates can be entered, with necessary error handling used, and the aforementioned current calendar and water year predefined choices are available in a dropdown to users.

The Angular Material Datepicker has been put on hold for now, and will hopefully will be updated by Google in the future. Closing this issue.
