### ISSUE TITLE
Need JSON application configuration file

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-snodas-ng#18]
The application needs a JSON configuration file similar to InfoMapper that can be used for configuration information.   I see that there is an `assets/map-config.json`.  Maybe change that to `app-config.json`.   The existing properties are probably OK.  The following properties are needed:

1. `version`, similar to InfoMapper.
2. Google Analytics, similar to InfoMapper, which will be used to automate updating the `index.html` Google Analytics code.  We will need to consult with the State on how they want to configure that for their system.

**Comment by Nightsphere** [comment]
The `map-config.json` file has been changed to `app-config.json`, and takes both app and map properties. Google Analytics can be used in the future. Closing this issue.
