### ISSUE TITLE
Switch default background to USGS Topo

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-snodas-ng#23]
The background is currently configured as a MapBox background using an account from the original software developer.  This is fragile because that account might be closed.  Instead, switch the background to the USGS Topo tile server that is used in InfoMapper.  Make this the default for now (OK to put in configuration file, especially if can just swap out the configuration file URL with other server if necessary).

Right now don't do the multiple background layers and hamburger menu.  Let's see if we can get funding to do more of that type of work.   Since this is not using InfoMapper map configuration, maybe the config file would eventually have a list of background URLs.

I also don't want to enhance the SNODAS app to much if the InfoMapper can serve as a more general tool.

```
https://basemap.nationalmap.gov/ArcGIS/rest/services/USGSTopo/MapServer/tile/{z}/{y}/{x}
```

**Comment by Nightsphere** [comment]
The USGS Topo has been added to the `app-config.json` file as the tile map. Closing the issue.
