### ISSUE TITLE
Add script to deploy the application to the State's GCP

### ISSUE THREAD

**Issue by smalers** [OpenWaterFoundation/owf-app-snodas-ng#27]
The existing `snodas.state.co.us` GCP storage bucket has the following top folders:

* `app` - legacy HTML application
* `data` - data folders, used by legacy and new application
* `test` - not sure

With the goal of keeping the old application around for a bit, and building on experience with other applications, I recommend the following to deploy the latest Angular application.

* Deploy to a versioned folder such as top level `2.0.0` folder, under which will be all the normal Angular files including `index.html`, `assets`, etc.
* Also deploy to top level `latest` folder.  This is a copy of the most recent versioned folder that is OK for production use.
* The Poudre Basin Information website is handled this way and I've used with other application.  The upload script can prompt for conformation before doing the copy.  It is important to NOT overwrite any existing folders, especially if "synchronize".
* The script could be called `build-util/copy-to-co-dnr-gcp.bash` to be consistent with other State work.

The above allows the URL to be something like:  `https://snodas.state.co.us/latest/` or `https://snodas.state.co.us/2.0.0`, the latter being useful for testing.  When in place, this will allow viewing the files uploaded by the GIS process.

**Comment by Nightsphere** [comment]
The script has been completed and lives in the `build-util/` folder as `copy-to-dnr-gcp.bash`. The [copy-to-owf-amazon-s3.sh](https://github.com/OpenWaterFoundation/owf-infomapper-poudre/blob/master/build-util/copy-to-owf-amazon-s3.sh) bash script to sync to AWS from the `owf-infomapper-poudre` repo was used as a foundation.

Closing the issue.
