### ISSUE TITLE
Get data from State server

### ISSUE THREAD

**Issue by Nightsphere** [OpenWaterFoundation/owf-app-snodas-ng#9]
Right now a sizable chunk of the graphs shown are retrieved from the State server, but a significant amount is still used from the
local testing data. This includes

* All dates
* Numbered Local ID basins.

Convert these to only using the server. Unfortunately, CORS is preventing the GET request, and everything I've found so far is implying it is a server-side issue, or offers work arounds that don't seem a robust solution:

* https://stackoverflow.com/questions/10636611/how-does-access-control-allow-origin-header-work
* https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe/43881141#43881141
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

**Comment by smalers** [comment]
Josh:

Is this what needs to be done?

[https://cloud.google.com/storage/docs/configuring-cors](https://cloud.google.com/storage/docs/configuring-cors)

**Comment by Nightsphere** [comment]
I believe all that needs to be done is:

```
[
    {
      "origin": ["*"],
    }
]
```

This should allow everything.

**Comment by smalers** [comment]
I added the [`set-gcp-cors-sh`]() script to set the CORS settings on the GCP bucket.  The setting needed to also set the method to `GET`.

**Comment by smalers** [comment]
Things seem to be working.   I'm closing this issue.
